### ISSUE TITLE
Does not specify API-version

### ISSUE THREAD

**Issue by srnyx** [webbukkit/Dynmap-Essentials#12]
When I try and load this plugin, I get an error that looks like this:
`16.11 09:03:45 [Server] WARN Plugin Dynmap-Essentials v0.91-SNAPSHOT does not specify an api-version.`

**Comment by srnyx** [comment]
Does this not affect anything?
Because no one has replied...

**Comment by DrBot7** [comment]
> Does this not affect anything?
> Because no one has replied...

For most plugins, it shouldn't affect anything. I'd assume that if you aren't experiencing any problems, it's not a problem.
